export const authConstant = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstant = {
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE"
}
export const categoryConstant = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS: 'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE: 'GET_ALL_CATEGORIES_FAILURE',
}

export const productConstant = {
    GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS: 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE: 'GET_ALL_PRODUCTS_FAILURE',
}

export const cartConstant={
    UPDATE_CART_REQUEST:"UPDATE_CART_REQUEST",
    UPDATE_CART_SUCCESS:"UPDATE_CART_SUCCESS",
    UPDATE_CART_FAILURE:"UPDATE_CART_FAILURE",
    INCREASE_CART_REQUEST:"INCREASE_CART_REQUEST",
    INCREASE_CART_SUCCESS:"INCREASE_CART_SUCCESS",
    INCREASE_CART_FAILURE:"INCREASE_CART_FAILURE",
    DECREASE_CART_REQUEST:"DECREASE_CART_REQUEST",
    DECREASE_CART_SUCCESS:"DECREASE_CART_SUCCESS",
    DECREASE_CART_FAILURE:"DECREASE_CART_FAILURE",
    REMOVE_CART_REQUEST:"REMOVE_CART_REQUEST",
    REMOVE_CART_SUCCESS:"REMOVE_CART_SUCCESS",
    REMOVE_CART_FAILURE:"REMOVE_CART_FAILURE"

}

export const orderConstant = {
    ORDER_PLACED_REQUEST: "ORDER_PLACED_REQUEST",
    ORDER_PLACED_SUCCESS: "ORDER_PLACED_SUCCESS",
    ORDER_PLACED_FAILURE: "ORDER_PLACED_FAILURE",
    ORDERS_BY_ID_FETCHED_REQUEST: "ORDERS_BY_ID_FETCHED_REQUEST",
    ORDERS_BY_ID_FETCHED_SUCCESS: "ORDERS_BY_ID_FETCHED_SUCCESS",
    ORDERS_BY_ID_FETCHED_FAILURE: "ORDERS_BY_ID_FETCHED_FAILURE",
    ORDERS_FETCHED_REQUEST: "ORDERS_FETCHED_REQUEST",
    ORDERS_FETCHED_SUCCESS: "ORDERS_FETCHED_SUCCESS",
    ORDERS_FETCHED_FAILURE: "ORDERS_FETCHED_FAILURE"
}

export const messageConstant={
    ADD_MESSAGE_REQUEST:"ADD_MESSAGE_REQUEST",
    ADD_MESSAGE_SUCCESS:"ADD_MESSAGE_SUCCESS",
    ADD_MESSAGE_FAILURE:"ADD_MESSAGE_FAILURE"
}
